package com.byebye.chapterTwo.global.auth.exception;

@kotlin.Metadata(mv = {1, 9, 0}, k = 1, xi = 48, d1 = {"\u0000\u0016\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0004\u0018\u00002\u00060\u0001j\u0002`\u0002B\r\u0012\u0006\u0010\u0003\u001a\u00020\u0004\u00a2\u0006\u0002\u0010\u0005R\u0011\u0010\u0003\u001a\u00020\u0004\u00a2\u0006\b\n\u0000\u001a\u0004\b\u0006\u0010\u0007\u00a8\u0006\b"}, d2 = {"Lcom/byebye/chapterTwo/global/auth/exception/CustomException;", "Ljava/lang/RuntimeException;", "Lkotlin/RuntimeException;", "customErrorCode", "Lcom/byebye/chapterTwo/global/auth/exception/CustomErrorCode;", "(Lcom/byebye/chapterTwo/global/auth/exception/CustomErrorCode;)V", "getCustomErrorCode", "()Lcom/byebye/chapterTwo/global/auth/exception/CustomErrorCode;", "chapterTwo"})
public final class CustomException extends java.lang.RuntimeException {
    @org.jetbrains.annotations.NotNull()
    private final com.byebye.chapterTwo.global.auth.exception.CustomErrorCode customErrorCode = null;
    
    public CustomException(@org.jetbrains.annotations.NotNull()
    com.byebye.chapterTwo.global.auth.exception.CustomErrorCode customErrorCode) {
        super();
    }
    
    @org.jetbrains.annotations.NotNull()
    public final com.byebye.chapterTwo.global.auth.exception.CustomErrorCode getCustomErrorCode() {
        return null;
    }
}